// ---------- Sync primitives ----------

/**
 * Base shape for any record that can be synced between devices.
 * - `updatedAt`: ISO timestamp of the last content change (any device).
 * - `deletedAt`: soft-delete tombstone. Present (non-null) only after a sync
 *   has observed a deletion — local lists simply drop the record.
 * Conflict policy is last-write-wins based on `updatedAt`.
 */
export interface SyncEntity {
  id: string;
  updatedAt: string; // ISO 8601
  deletedAt?: string | null;
}

/** Collections that participate in the sync engine. */
export type SyncCollection = "snippets" | "notes" | "tasks";

/**
 * Full-state snapshot of one collection as stored on a device.
 * `updatedAt` is the moment the snapshot was taken.
 */
export interface SyncSnapshot<T extends SyncEntity = SyncEntity> {
  updatedAt: string;
  items: T[];
}

export type SyncPhase = "idle" | "syncing" | "success" | "error";

export interface SyncStatus {
  phase: SyncPhase;
  lastSyncAt: string | null;
  pendingCollections: SyncCollection[];
  error?: string;
  needsMigration?: boolean;
}

// ---------- Auth / device ----------

export interface AppUser {
  id: string;
  email: string;
  name: string;
  avatar_url: string | null;
}

export interface AppDevice {
  deviceId: string;
  name: string;
}

// ---------- Code Snippet Manager ----------

export interface Snippet extends SyncEntity {
  title: string;
  language: string;
  code: string;
}

// ---------- Notes ----------

export interface NoteBlock {
  id: string;
  type: "text" | "image";
  content: string;
  /** Present when type === "image" (data URL generated by FileReader). */
  src?: string;
}

export interface Note extends SyncEntity {
  title: string;
  blocks: NoteBlock[];
}

// ---------- Task Board ----------

export type TaskStatus = "Backlog" | "In Progress" | "Review" | "Done";

export interface Task extends SyncEntity {
  title: string;
  description: string;
  createdAt: string;
  deadline: string;
  status: TaskStatus;
}